defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  username: <%= ENV['ST_SNR_USR'] %>
  password: <%= ENV['ST_SNR_PSS'] %>

development:
  database: social_network_rails_dev
  <<: *defaults

test:
  database: social_network_rails_test
  <<: *defaults

production:
  database: social_network_rails_prod
  <<: *defaults